name: Check Markdown links

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # See: https://github.com/tcort/github-action-markdown-link-check
      - name: Check Markdown links
        uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          file-path: './README.md'

